### ISSUE TITLE
Web:Archive does not Scan Packages

### ISSUE THREAD

**Issue by idefixcert** [buschmais/jqassistant#389]
The WebArchive is not scanned for Packages
MATCH (n:Package) where n.fqn contains "web.filter" RETURN n LIMIT 25

but it is scanned for classes
MATCH (n:Class) where n.fqn contains "web.filter" RETURN n LIMIT 25

Can anyone Help?

**Comment by DirkMahler** [comment]
This bug is currently being fixed, packages defined in "WEB-INF/classes" folders are affected. If you're using the CLI please download the latest snapshot from https://oss.sonatype.org/content/repositories/snapshots/com/buschmais/jqassistant/distribution/jqassistant.distribution/1.1.4-SNAPSHOT/. An bug fix release will soon be available.

**Comment by DirkMahler** [comment]
The 1.1.4 release is now available from http://jqassistant.org, the issue is fixed there.
